RUN rm -rf apache-tomcat-9.0.62.tar.gz

#Install git
RUN apt-get install -y git      
WORKDIR /home/ubuntu/
RUN git clone https://github.com/vsowjanyarani/maven2.git

#Set working directory
WORKDIR /home/ubuntu/maven2/web-project/
RUN ls
RUN pwd
RUN mvn clean install
RUN ls
RUN pwd
WORKDIR /home/ubuntu/maven2/web-project/target/
RUN ls
RUN pwd
RUN cp -r web-project.war /tomcat/webapps
RUN ls
#Enter environment variable
ENV keys=aatmani
