version: "3.3"
services:
  elk:
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
          ports:
                 - "9200:9200"
  kibana:
          image: docker.elastic.co/kibana/kibana:7.10.1
          ports:
                 - "5601:5601"
  logstash:
          image: docker.elastic.co/logstash/logstash:7.10.1
          ports:
                 - "5044:5044"
